name: Build and deploy ASP.Net Core app to Azure Web App - BitBeak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build with dotnet
        run: dotnet build BitBeakAPI.csproj --configuration Release
      - name: dotnet publish
        run: dotnet publish BitBeakAPI.csproj -c Release -o ./myapp
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp
      - name: List files in the deploy directory
        run: ls ./myapp
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BitBeak'
          slot-name: 'Production'
          package: ./myapp
