name: Build and deploy ASP.Net Core app to Azure Web App - BitBeak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build with dotnet
        run: dotnet build BitBeakAPI.csproj --configuration Release
      - name: dotnet publish
        run: dotnet publish BitBeakAPI.csproj -c Release -o ./myapp
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{
                  "clientId": "${{ secrets.AZUREAPPSERVICE_CLIENTID_A900E27F8E7B4AD9A2017248ED282886 }}",
                  "tenantId": "${{ secrets.AZUREAPPSERVICE_TENANTID_B14CF491794A42B6AF3416F651F91224 }}",
                  "subscriptionId": "${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B195587C931A45DEAEC6865DC8A49571 }}"
                }'
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BitBeak'
          slot-name: 'Production'
          package: ./myapp
